name: trackly
services:
  db:
    platform: linux/amd64
    container_name: trackly_db
    image: postgis/postgis:17-3.5-alpine # ghcr.io/baosystems/postgis:17-master
    restart: unless-stopped
    environment:
      POSTGRES_DB: trackly
      POSTGRES_USER: trackly
      POSTGRES_PASSWORD: trackly
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./backend/schema.sql:/app/schema.sql
  backend:
    container_name: trackly_backend
    restart: unless-stopped
    build: ./backend
    environment:
      DATABASE_URL: postgres://trackly:trackly@db:5432/trackly
      RUST_LOG: trace # info | debug | trace
    depends_on:
      - db
    ports:
      - 8080:8080
  frontend:
    container_name: trackly_frontend
    restart: unless-stopped
    build: ./frontend
    volumes:
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
