-- Migration: Add user accounts and authentication tables
-- Part of user-accounts-specification.md implementation

-- ============================================================================
-- Table: users
-- ============================================================================
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,                     -- Generated by App (UUIDv7)
    google_sub VARCHAR(255) UNIQUE NOT NULL,      -- Google subject ID
    email VARCHAR(255) UNIQUE NOT NULL,           -- From Google ID token
    name VARCHAR(255) NOT NULL DEFAULT '',        -- From Google ID token
    nickname VARCHAR(50),                         -- User-chosen display name
    avatar_url VARCHAR(512),                      -- Google profile picture
    roles TEXT[] NOT NULL DEFAULT ARRAY['user']::text[],
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for users table
CREATE INDEX IF NOT EXISTS idx_users_google_sub ON users(google_sub);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at DESC);

-- Trigger to update updated_at on users
DROP TRIGGER IF EXISTS set_users_updated_at ON users;
CREATE TRIGGER set_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE users IS 'User accounts linked to Google OAuth2';
COMMENT ON COLUMN users.user_id IS 'Primary key, UUIDv7 generated by application';
COMMENT ON COLUMN users.google_sub IS 'Unique Google subject ID from ID token';
COMMENT ON COLUMN users.nickname IS 'User-chosen display name, 1-50 chars';

-- ============================================================================
-- Table: user_refresh_tokens
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    family_id UUID NOT NULL,                      -- Token family for chain revocation
    token_hash VARCHAR(64) NOT NULL,              -- SHA256(refresh_token)
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    revoked_at TIMESTAMPTZ                        -- For token invalidation
);

-- Indexes for user_refresh_tokens table
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON user_refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_hash ON user_refresh_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON user_refresh_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON user_refresh_tokens(family_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_active ON user_refresh_tokens(revoked_at) 
    WHERE revoked_at IS NULL;

COMMENT ON TABLE user_refresh_tokens IS 'Refresh tokens for JWT renewal with family-based revocation';
COMMENT ON COLUMN user_refresh_tokens.family_id IS 'Token family ID for chain revocation on replay';
COMMENT ON COLUMN user_refresh_tokens.token_hash IS 'SHA256 hash of the refresh token (never store plaintext)';

-- ============================================================================
-- Table: login_attempts
-- ============================================================================
CREATE TABLE IF NOT EXISTS login_attempts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE SET NULL,
    ip_address INET,
    user_agent TEXT,
    method VARCHAR(50) NOT NULL DEFAULT 'google_oauth',
    success BOOLEAN NOT NULL,
    failure_reason VARCHAR(100),                  -- "invalid_code", "network_error", etc.
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    request_id UUID                               -- For tracing
);

-- Indexes for login_attempts table
CREATE INDEX IF NOT EXISTS idx_login_attempts_user_id ON login_attempts(user_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_login_attempts_ip ON login_attempts(ip_address, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_login_attempts_timestamp ON login_attempts(timestamp DESC);

COMMENT ON TABLE login_attempts IS 'Audit log for authentication attempts (success and failure)';
COMMENT ON COLUMN login_attempts.failure_reason IS 'Generic reason for failure (never expose user enumeration)';

-- ============================================================================
-- Modify tracks table: Add user_id for authenticated ownership
-- ============================================================================
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(user_id) ON DELETE CASCADE;

-- Index for user_id lookups
CREATE INDEX IF NOT EXISTS idx_tracks_user_id ON tracks(user_id, created_at DESC);

-- Composite index for listing user's public tracks
CREATE INDEX IF NOT EXISTS idx_tracks_user_public ON tracks(user_id, is_public) WHERE is_public = true;

-- Indexes for common filters and sorting on account lists
CREATE INDEX IF NOT EXISTS idx_tracks_user_created_length ON tracks(user_id, created_at DESC, length_km);
CREATE INDEX IF NOT EXISTS idx_tracks_user_elevation ON tracks(user_id, elevation_gain DESC);

-- Update is_public default to false (privacy-by-default for new tracks)
-- Note: Existing tracks retain their current is_public value (TRUE)
ALTER TABLE tracks ALTER COLUMN is_public SET DEFAULT false;

COMMENT ON COLUMN tracks.user_id IS 'Owner user ID for authenticated users (NULL for anonymous session-based tracks)';

-- ============================================================================
-- Modify pois table: Add user_id for authenticated ownership
-- ============================================================================
ALTER TABLE pois ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(user_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pois_user_id ON pois(user_id);

COMMENT ON COLUMN pois.user_id IS 'Owner user ID for authenticated users (NULL for session-based POIs)';

-- ============================================================================
-- Modify poi_audit_log table: Add user_id for better tracing
-- ============================================================================
ALTER TABLE poi_audit_log ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(user_id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_poi_audit_log_user_id ON poi_audit_log(user_id);

COMMENT ON COLUMN poi_audit_log.user_id IS 'User who performed the action (NULL for anonymous)';
